name: run rust checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: run tests
        run: cargo test

  check-windows:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: run tests
        run: cargo test
